from django.urls import path

from apps.organizacion.apis.views import (
    AsignaturaCreateView,
    AsignaturaDetailUpdateDeleteView,
    AsignaturaListView,
    EducacionNivelListView,
    GradoEscolarCreateView,
    GradoEscolarDetailUpdateDeleteView,
    GradoEscolarListView,
    InstitucionDetailUpdateDeleteView,
    InstitucionListCreateView,
    InstitucionUsuarioView,
    PlanEstudioCreateView,
    PlanEstudioDetailUpdateDeleteView,
    PlanEstudioListView,
    RolListView,
    UsuarioRolDetailUpdateDeleteView,
    UsuarioRolListCreateView,
    UsuarioRolRolesView,
    UsuarioRolToggleView,
)

urlpatterns = [
    path('instituciones/', InstitucionListCreateView.as_view(), name='institucion-list-create'),
    path('instituciones/<int:pk>/', InstitucionDetailUpdateDeleteView.as_view(), name='institucion-detail-update-delete'),
    path('instituciones/usuario/', InstitucionUsuarioView.as_view(), name='institucion-usuario'),
    path('roles/', RolListView.as_view(), name='rol-list'),
    path('usuarioroles/', UsuarioRolListCreateView.as_view(), name='usuariorol-list-create'),
    path('usuarioroles/roles/', UsuarioRolRolesView.as_view(), name='usuariorol-roles'),
    path('usuarioroles/<int:pk>/estado/', UsuarioRolToggleView.as_view(), name='usuariorol-toggle'),
    path('usuarioroles/<int:pk>/', UsuarioRolDetailUpdateDeleteView.as_view(), name='usuariorol-detail-update-delete'),
    path('planes-estudio/instituciones/<int:institucion_id>/', PlanEstudioListView.as_view(), name='planestudio-list'),
    path('planes-estudio/', PlanEstudioCreateView.as_view(), name='planestudio-create'),
    path('planes-estudio/<int:pk>/', PlanEstudioDetailUpdateDeleteView.as_view(), name='planestudio-detail-update-delete'),
    path('grados-escolares/planes-estudio/<int:plan_estudio_id>/', GradoEscolarListView.as_view(), name='gradoescolar-list'),
    path('grados-escolares/', GradoEscolarCreateView.as_view(), name='gradoescolar-create'),
    path('grados-escolares/<int:pk>/', GradoEscolarDetailUpdateDeleteView.as_view(), name='gradoescolar-detail-update-delete'),
    path('asignaturas/grados-escolares/<int:grado_escolar_id>/', AsignaturaListView.as_view(), name='asignatura-list'),
    path('asignaturas/', AsignaturaCreateView.as_view(), name='asignatura-create'),
    path('asignaturas/<int:pk>/', AsignaturaDetailUpdateDeleteView.as_view(), name='asignatura-detail-update-delete'),
    path('educacion-niveles/', EducacionNivelListView.as_view(), name='educacionnivel-list'),
]
