# Generated by Django 6.0.6 on 2026-07-10 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de actualización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='nombre')),
                ('ruc', models.CharField(max_length=20, unique=True, verbose_name='RUC')),
            ],
            options={
                'verbose_name': 'institución educativa',
                'verbose_name_plural': 'instituciones educativas',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('AUTORIDAD_ACADEMICA', 'Autoridad académica'), ('DOCENTE', 'Docente'), ('SECRETARIA', 'Secretaria'), ('ESTUDIANTE', 'Estudiante'), ('DECE', 'DECE')], max_length=50, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_activo', models.BooleanField(default=True, verbose_name='es activo')),
                ('fecha_desde', models.DateField(blank=True, null=True, verbose_name='fecha desde')),
                ('fecha_hasta', models.DateField(blank=True, null=True, verbose_name='fecha hasta')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='organizacion.institucion', verbose_name='institución')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='organizacion.rol', verbose_name='rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'asignación de rol',
                'verbose_name_plural': 'asignaciones de roles',
                'constraints': [models.UniqueConstraint(condition=models.Q(('es_activo', True)), fields=('usuario', 'rol', 'institucion'), name='unique_usuario_rol_institucion_activo')],
            },
        ),
    ]
