# Generated by Django 6.0.6 on 2026-07-10 17:00

from django.db import migrations


def seed_roles(apps, schema_editor):
    Rol = apps.get_model('organizacion', 'Rol')
    roles_data = [
        ('ADMINISTRADOR', 'Administrador'),
        ('AUTORIDAD_ACADEMICA', 'Autoridad académica'),
        ('DOCENTE', 'Docente'),
        ('SECRETARIA', 'Secretaria'),
        ('ESTUDIANTE', 'Estudiante'),
        ('DECE', 'DECE'),
    ]
    for codigo, _ in roles_data:
        Rol.objects.get_or_create(nombre=codigo)


def reverse_seed_roles(apps, schema_editor):
    Rol = apps.get_model('organizacion', 'Rol')
    Rol.objects.filter(nombre__in=[
        'ADMINISTRADOR',
        'AUTORIDAD_ACADEMICA',
        'DOCENTE',
        'SECRETARIA',
        'ESTUDIANTE',
        'DECE',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0001_inicial'),
    ]

    operations = [
        migrations.RunPython(seed_roles, reverse_seed_roles),
    ]
