# Generated by Django 6.0.6 on 2026-07-14 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0002_seed_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducacionNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de actualización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('pp_minutos', models.PositiveIntegerField(verbose_name='carga pedagógica mínima (minutos)')),
                ('pp_semana_minimo', models.PositiveIntegerField(verbose_name='carga pedagógica mínima semanal')),
            ],
            options={
                'verbose_name': 'nivel educativo',
                'verbose_name_plural': 'niveles educativos',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='EducacionSubNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de actualización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('pp_semana_minimo', models.PositiveIntegerField(verbose_name='carga pedagógica mínima semanal')),
                ('educacion_nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subniveles', to='organizacion.educacionnivel', verbose_name='nivel educativo')),
            ],
            options={
                'verbose_name': 'subnivel educativo',
                'verbose_name_plural': 'subniveles educativos',
                'ordering': ('nombre',),
                'unique_together': {('nombre', 'educacion_nivel')},
            },
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_activo', models.BooleanField(default=False, verbose_name='es activo')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de actualización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_estudio', to='organizacion.institucion', verbose_name='institución')),
            ],
            options={
                'verbose_name': 'plan de estudio',
                'verbose_name_plural': 'planes de estudio',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='GradoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de actualización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('orden', models.PositiveIntegerField(verbose_name='orden')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados_escolares', to='organizacion.educacionnivel', verbose_name='nivel educativo')),
                ('subnivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grados_escolares', to='organizacion.educacionsubnivel', verbose_name='subnivel educativo')),
                ('plan_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados_escolares', to='organizacion.planestudio', verbose_name='plan de estudio')),
            ],
            options={
                'verbose_name': 'grado escolar',
                'verbose_name_plural': 'grados escolares',
                'ordering': ('orden', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de actualización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('pp_semana_minimo', models.PositiveIntegerField(verbose_name='carga pedagógica mínima semanal')),
                ('grado_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='organizacion.gradoescolar', verbose_name='grado escolar')),
            ],
            options={
                'verbose_name': 'asignatura',
                'verbose_name_plural': 'asignaturas',
                'ordering': ('nombre',),
                'unique_together': {('nombre', 'grado_escolar')},
            },
        ),
        migrations.AddConstraint(
            model_name='planestudio',
            constraint=models.UniqueConstraint(condition=models.Q(('es_activo', True)), fields=('institucion',), name='unique_plan_vigente_por_institucion'),
        ),
        migrations.AlterUniqueTogether(
            name='planestudio',
            unique_together={('nombre', 'institucion')},
        ),
        migrations.AlterUniqueTogether(
            name='gradoescolar',
            unique_together={('nombre', 'plan_estudio')},
        ),
    ]
